// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZ0Mivi-PKObQ4ha3pYNenUcG2wQ-oZk',
    appId: '1:806904878638:web:f11edaefc69343e1e971bf',
    messagingSenderId: '806904878638',
    projectId: 'acesstrans',
    authDomain: 'acesstrans.firebaseapp.com',
    storageBucket: 'acesstrans.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHAliIwuneL7tWg9S-DW-BwRXN1Lzo1mE',
    appId: '1:806904878638:android:4fae7d4a12ab2547e971bf',
    messagingSenderId: '806904878638',
    projectId: 'acesstrans',
    storageBucket: 'acesstrans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzv7aKid4LBZeQyNwJpnte-hodVyzx0I',
    appId: '1:806904878638:ios:9dbf96b08e71f7e9e971bf',
    messagingSenderId: '806904878638',
    projectId: 'acesstrans',
    storageBucket: 'acesstrans.firebasestorage.app',
    iosClientId: '806904878638-c3b8h5hmt2evclofe3vsid97par7o8sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.acesstrans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjzv7aKid4LBZeQyNwJpnte-hodVyzx0I',
    appId: '1:806904878638:ios:9dbf96b08e71f7e9e971bf',
    messagingSenderId: '806904878638',
    projectId: 'acesstrans',
    storageBucket: 'acesstrans.firebasestorage.app',
    iosClientId: '806904878638-c3b8h5hmt2evclofe3vsid97par7o8sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.acesstrans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlZ0Mivi-PKObQ4ha3pYNenUcG2wQ-oZk',
    appId: '1:806904878638:web:f844bdb4e07750dfe971bf',
    messagingSenderId: '806904878638',
    projectId: 'acesstrans',
    authDomain: 'acesstrans.firebaseapp.com',
    storageBucket: 'acesstrans.firebasestorage.app',
  );
}
